### ISSUE TITLE
Error: Uncaught TypeError: Cannot read properties of null (reading 'setLatLng') @ https://jiririchter.github.io/WRFDomainWizard/build/js/wrf-domain-wizard.js:27451

### ISSUE THREAD

**Issue by kuikig** [JiriRichter/WRFDomainWizard#50]
Error: Uncaught TypeError: Cannot read properties of null (reading 'setLatLng')
Timestamp: 2024-10-14T08:40:31.385Z
Source: https://jiririchter.github.io/WRFDomainWizard/build/js/wrf-domain-wizard.js
Line: 27451
Stack:
TypeError: Cannot read properties of null (reading 'setLatLng')
    at e.update (https://jiririchter.github.io/WRFDomainWizard/build/js/wrf-domain-wizard.js:27451:26)
    at modifyDxDy (https://jiririchter.github.io/WRFDomainWizard/build/js/wrf-domain-wizard.js:28040:16)
    at HTMLButtonElement.<anonymous> (https://jiririchter.github.io/WRFDomainWizard/build/js/wrf-domain-wizard.js:28046:7)
    at HTMLButtonElement.dispatch (https://jiririchter.github.io/WRFDomainWizard/build/lib/jquery.min.js:2:40035)
    at v.handle (https://jiririchter.github.io/WRFDomainWizard/build/lib/jquery.min.js:2:38006)

**Comment by JiriRichter** [comment]
@kuikig, thank you for reporting this issue. Would you able to provide steps I can follow to reproduce this?

**Comment by JiriRichter** [comment]
From the stack trace contains modifyDxDy  which is called when the user clicks the mod buttons for DX/DY. I was not able to repro this.

**Comment by JiriRichter** [comment]
Closing as no repro
