### ISSUE TITLE
Error: Uncaught Error: Undefined value @ https://jiririchter.github.io/WRFDomainWizard/build/js/wrf-domain-wizard.js:17534

### ISSUE THREAD

**Issue by AimerFleur** [JiriRichter/WRFDomainWizard#52]
Error: Uncaught Error: Undefined value
Timestamp: 2024-10-21T02:36:42.756Z
Source: https://jiririchter.github.io/WRFDomainWizard/build/js/wrf-domain-wizard.js
Line: 17534
Stack:
Error: Undefined value
    at Function._formatValue (https://jiririchter.github.io/WRFDomainWizard/build/js/wrf-domain-wizard.js:17534:17)
    at Function._formatValue (https://jiririchter.github.io/WRFDomainWizard/build/js/wrf-domain-wizard.js:17536:33)
    at Function.formatSection (https://jiririchter.github.io/WRFDomainWizard/build/js/wrf-domain-wizard.js:17568:74)
    at WPSNamelist.toString (https://jiririchter.github.io/WRFDomainWizard/build/js/wrf-domain-wizard.js:17894:29)
    at WPSSaveDialog.show (https://jiririchter.github.io/WRFDomainWizard/build/js/wrf-domain-wizard.js:28220:55)
    at HTMLButtonElement.<anonymous> (https://jiririchter.github.io/WRFDomainWizard/build/js/wrf-domain-wizard.js:30226:23)
    at HTMLButtonElement.dispatch (https://jiririchter.github.io/WRFDomainWizard/build/lib/jquery.min.js:2:40035)
    at v.handle (https://jiririchter.github.io/WRFDomainWizard/build/lib/jquery.min.js:2:38006)

**Comment by HathewayWill** [comment]
> Error: Uncaught Error: Undefined value
> Timestamp: 2024-10-21T02:36:42.756Z
> Source: https://jiririchter.github.io/WRFDomainWizard/build/js/wrf-domain-wizard.js
> Line: 17534
> Stack:
> Error: Undefined value
>     at Function._formatValue (https://jiririchter.github.io/WRFDomainWizard/build/js/wrf-domain-wizard.js:17534:17)
>     at Function._formatValue (https://jiririchter.github.io/WRFDomainWizard/build/js/wrf-domain-wizard.js:17536:33)
>     at Function.formatSection (https://jiririchter.github.io/WRFDomainWizard/build/js/wrf-domain-wizard.js:17568:74)
>     at WPSNamelist.toString (https://jiririchter.github.io/WRFDomainWizard/build/js/wrf-domain-wizard.js:17894:29)
>     at WPSSaveDialog.show (https://jiririchter.github.io/WRFDomainWizard/build/js/wrf-domain-wizard.js:28220:55)
>     at HTMLButtonElement.<anonymous> (https://jiririchter.github.io/WRFDomainWizard/build/js/wrf-domain-wizard.js:30226:23)
>     at HTMLButtonElement.dispatch (https://jiririchter.github.io/WRFDomainWizard/build/lib/jquery.min.js:2:40035)
>     at v.handle (https://jiririchter.github.io/WRFDomainWizard/build/lib/jquery.min.js:2:38006)

@AimerFleur 

Were you trying to delete the parent domain d01 from the namelist wps tool?

**Comment by JiriRichter** [comment]
Closing as no repro
